// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GerarKMZ(arg1:main.KMZRequest):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SelectFolder():Promise<string>;
